#pragma once

#define CXXGraph_VERSION "4.1.0"
#define CXXGraph_VERSION_MAJOR "@PROJECT_VERSION_MAJOR"
#define CXXGraph_VERSION_MINOR "@PROJECT_VERSION_MINOR"
#define CXXGraph_VERSION_PATCH "@PROJECT_VERSION_PATCH"
